version: '3'

services:
  cc-novnc:
    container_name: cc-novnc
    privileged: true # For setup FUSE filesystem for AppImage
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./save:/cc-novnc/save
      - ./conf/supervisor:/etc/supervisor
      - ./conf/openbox:/etc/xdg/openbox
    network_mode: "bridge"
