version: '3'

services:
  cc-novnc:
    container_name: cc-novnc
    privileged: true # For setup FUSE filesystem for AppImage
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./save:/cc-novnc/save
    networks:
      - nginx-network # Ensure it's on the same network as Nginx Proxy Manager

networks:
  nginx-network:
    external: true
