version: '3'

services:
  cc-vnc:
    container_name: cc-vnc
    privileged: true # For setup FUSE filesystem for AppImage
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./save:/cc-vnc/save
      - ./conf/supervisor:/etc/supervisor
      - ./conf/openbox:/etc/xdg/openbox
    network_mode: "bridge"
